### ISSUE TITLE
Stabilizer errata

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Stabilizer#10]
- [x] ceramic capacitor colliding with J12 connector
- [x] add P3V3MP supply path for stand-alone operation. EEPROM may block the I2C bus
- [x] REF VCC testpoint label wrong - should be 7V instead of 12V
- [x] spelling error under CPLD (remove)

**Comment by gkasprow** [comment]
- [ ] missing connection of 2V reference port with reference label. Short pin 6 RN3C with pin 3 RN4C

**Comment by jmilczarek** [comment]
- [ ] micro USB port placed too far beyond PCB outline - creates tension of the front panel

**Comment by gkasprow** [comment]
@jmilczarek the connector was placed on purpose to protrude via the panel, otherwise one won't be able to fully plug the USB plug. So one needs to enlarge the panel hole. Please post the image from front side. You can drag and drop the image to the github.

**Comment by gkasprow** [comment]
- [ ] add RN designators on silkscreen

**Comment by dtcallcock** [comment]
C164 should be 82pF, not 390pF.

**Comment by gkasprow** [comment]
- [ ] 3V3MP LED (LD11) annotated as P3V3

**Comment by hartytp** [comment]
> 3V3MP LED (LD11) annotated as P3V3

Is this something that's just on the EEM connector? Should it be annotated something like 3V3_EEM? One thing I found confusing when I first powered the board on is that the 3V3 light doesn't come on (usually, one LED in the strip of power on lights not coming on is a very bad sign with these designs, but here it's normal).

**Comment by gkasprow** [comment]
True, MP means management power which is also confusing.

**Comment by jordens** [comment]
Please label it (P)3V3(_)MP.

* We have that label on many other places on many other EEMs. Changing it is inconsistent and adds confusion.
* 3V3_MP being off hasn't been a problem in other EEMs.
* 3V3_EEM does not indicate that it can be off anymore than 3V3_MP does. It would not help.
* I don't see the problem with the label. Management power has clear meaning and I can't come up with something clearer (EEM certainly isn't clearer).
* But it would be good if you add that alternative supply path. It enables (a) standalone ops with the EEPROM and (b) enables driving another EEM (modulo pinout).

**Comment by gkasprow** [comment]
OK. The last request is already on top of this issue.

**Comment by airwoodix** [comment]
- [ ] fix front panel or schematic LEDs labeling (rather the latter)
On my v1.0 board + FP, I have the following:
  - FP_LED0 (green, PD5) <-> L2 on FP
  - FP_LED1 (red, PD6) <-> L3 on FP
  - FP_LED2 (green, PG4) <-> L0 on FP
  - FP_LED3 (red, PD12) <-> L1 on FP
