### ISSUE TITLE
panel mechanics

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#11]
* the usb connector has enough depth to pull it back a mm at least to have it not bend the panel
* the MCX are low in the panel and they are too close to the panel, touching it with the pins.
* micro usb and RJ45 fit together nicely, even at the same time

![image](https://user-images.githubusercontent.com/1338946/54522833-77674e80-496e-11e9-8bc8-4991abc20bc4.png)
![image](https://user-images.githubusercontent.com/1338946/54522854-85b56a80-496e-11e9-8125-12bcb55ee1de.png)

**Comment by gkasprow** [comment]
OK, moved the USB by 1mm.

**Comment by gkasprow** [comment]
Moved MCX by 0.5mm

**Comment by hartytp** [comment]
Can we close this?
