### ISSUE TITLE
Flashing Stabilizer

### ISSUE THREAD

**Issue by kvziegler** [sinara-hw/Stabilizer#120]
Hello,

I am trying to flash the Stabilizer via the manual here: https://quartiq.de/stabilizer/setup.html

I have the Stabilizer v1.3.4 and the CPU JTAG pin-out on the card does not fit the recommended adapter (ST-Link V2-1 or later). Could you provide me with an adapter that is used to flash the binaries onto this version Stabilizer card? Thank you.

**Comment by jordens** [comment]
Just center it. It fits.

**Comment by gkasprow** [comment]
You can also use bootloader (jumper) and load the binaries over USB

**Comment by kvziegler** [comment]
Thank you, I flashed it via the bootloader.
