### ISSUE TITLE
smaller PoE module

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#14]
Do we really need 24W/30W here? Stabilizer itself will be less than 5 W. Maybe a 12W/15.4W PoE module would do fine and leave sufficient power for beefy things on the GPIO or AFE headers.

**Comment by hartytp** [comment]
12W works for me.

I'm designing an AFE mezzanine which will draw about 7W to power a flux-gate sensor. But, I wouldn't want to run that from PoE...

**Comment by gkasprow** [comment]
The price difference between 30W and 12W PoE module is negligible and it's better to use the same module across all designs.
