### ISSUE TITLE
add PoE isolation barrier

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#15]
It might be worth cleaning up the layout a bit to ensure we can live with the PoE requirements, e.g. 1.5kV impulse. This is also important for compliance.

**Comment by gkasprow** [comment]
True. So far the limiting factor is 0.6mm distance in some places.
For 1.5kV we need usually 1.5mm distance on the PCB. At the moment the Ethernet connector has distance between PoE and control signals of 1.1mm
There is also one trace below the PoE module I overlooked which has 0.15mm distance.

**Comment by gkasprow** [comment]
fixed.
