### ISSUE TITLE
DCDC switching leakage on DAC outputs

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#17]
I think I was seeing quite some update transients/glitching/digital feedthrough on the DAC outputs outside the 500 kHz bandwidth. A couple mV IIRC. I'll post shots if I find the time and if I can reproduce it. Did the AFE filter simulation include the non-ideal behavior of the opamps at higher frequencies?

**Comment by gkasprow** [comment]
I used standard TINA models. I don't know how accurately it behaves at higher frequencies.
The simulations are [here ](https://www.dropbox.com/sh/3x5q54i9ryabo9d/AABXV05j78ZGPZhp7ULNxNXpa?dl=0)

**Comment by jordens** [comment]
It was in fact not at the sample rate (500 kHz) but at one of the DCDC converter frequencies (400 kHz). 16 mVpp.

**Comment by hartytp** [comment]
Good catch, but ouch!

**Comment by jordens** [comment]
That was from the PoE module. I am using unshielded TP cables.
When powering it from the barrel connector there is still some other switching transient at 5mVpp and 500 kHz which I can't locate.

**Comment by gkasprow** [comment]
I'm not sure if I still have any Stabilized on the lab to check it.

**Comment by hartytp** [comment]
@jordens do you still see any of this noise if you look at the DAC outputs on the SMA?

**Comment by jordens** [comment]
Sure. That's where I generally look.

**Comment by gkasprow** [comment]
I took the Stabilizer home. I supplied it from the power bank to make sure there are no ground loops.
The output is the following:
![tek00001](https://user-images.githubusercontent.com/4325054/60076827-ce787e80-9728-11e9-892f-8dc49c97e716.png)

**Comment by gkasprow** [comment]
In my case the interference period is roughly 25us.

**Comment by hartytp** [comment]
Which smps is that? Is that at dc output of 0V?

**Comment by gkasprow** [comment]
That's funny. I switched the power off. And the signal looks similar.
![tek00000](https://user-images.githubusercontent.com/4325054/60076930-18616480-9729-11e9-9824-d407574f9b0d.png)

**Comment by dnadlinger** [comment]
> That's funny. I switched the power off. 

Switched the power off, as in the power to the circuit and it's actually external interference still?

**Comment by gkasprow** [comment]
there are ~2.8us spikes visible after I trigger the scope with <5ns pulses and turn averaging.
But none of the converters on the board works with such frequency
![tek00006](https://user-images.githubusercontent.com/4325054/60077979-5e1f2c80-972b-11e9-9913-428c28d9b856.png)

**Comment by gkasprow** [comment]
when I switch the power off, the bit interferences stay, but these small spikes go away.

**Comment by gkasprow** [comment]
All power rails are quiet, only P3V3 have 20mV ripples, but not correlated wit the output

**Comment by gkasprow** [comment]
![tek00007](https://user-images.githubusercontent.com/4325054/60078629-996e2b00-972c-11e9-82bf-f90be38501d4.png)

**Comment by gkasprow** [comment]
It looks like these spikes are caused by me. When I touch the board they appear, when I don't, they disappear.

**Comment by gkasprow** [comment]
they are caused by the power bank. When I connect only GND with power bank, they appear.

**Comment by gkasprow** [comment]
but they are induced only on the scope probe. When I touch the board GND,  at the crocodile clip, they are also there. SMA cable doesn't help much because we have CMC which has limited attenuation rate for such short pulses.

**Comment by hartytp** [comment]
Wrap a ferrite on your power and scope cable?

**Comment by gkasprow** [comment]
True, this could help for such a noise source.

**Comment by hartytp** [comment]
Worth a go.

Anyway, pick-up from external SMPSs is always an annoying issue.

**Comment by hartytp** [comment]
The bigger issue I saw -- and the one that concerns me most -- was the noise on the DAC output that scales with the programmed DAC voltage. See here https://github.com/sinara-hw/Stabilizer/issues/9#issuecomment-499091392

As this noise scales with the DAC voltage, it's definitely not due to an external source. Were you able to reproduce this?

**Comment by hartytp** [comment]
> they are caused by the power bank. When I connect only GND with power bank, they appear.

I've lost track. In your measurements did you see any noise at all on the DAC output that wasn't caused by pickup from external sources?

**Comment by gkasprow** [comment]
It looks that all I see comes from external sources. The noise you mentioned seems to be covered by them. I thought I'm living in a quiet spot. It is quiet, but not from EM point of view. Tomorrow I will connect it to the 12V battery directly and try to reproduce it.

**Comment by hartytp** [comment]
what DAC dc output voltages did you measure?

I guess it’s possible that what I’m seeing is just filtered amplified pick up that’s getting in to the dac ref circuit. Although if that’s really the case then it’s odd that I see so much more noise on the DAC than the ADC.

**Comment by hartytp** [comment]
I’ll try to find a screened box for stabilizer and take some more data.

Can you remind me of a on for a screened Eurocrats box that I can mount stabilizer in with its panel?

**Comment by gkasprow** [comment]
I observed default DAC output which is 0V.

**Comment by hartytp** [comment]
@glasprow ok. No the noise I see scales with the DAC output. If the output is 0V then you don’t see any noise. So you have to use a fw that programs it to full scale or something...

**Comment by gkasprow** [comment]
OK, I will have a look it tomorrow.

**Comment by hartytp** [comment]
:)

**Comment by gkasprow** [comment]
Do you have some simple binary that outputs max value? I don't want to mess up with setting toolchain.
If you could provide me binary I could load via DFU that would make my life simpler.

**Comment by hartytp** [comment]
@gkasprow sure, I'll send you something tomorrow.

What I will do is change this one line of @jordens firmware to set the DAC to a fixed value of `0xffff` https://github.com/quartiq/stabilizer/blob/d9aa3f440143f0567c1259b85b3051eef24cd349/src/main.rs#L806

@gkasprow I haven't flashed using DFU, but OpenOCD worked fine (the only slightly annoying thing was finding a recent version).

Generally, I was amazed how easy it was to build and flash the firmware. Following Robert's instructions and the [embedded rust book](https://rust-embedded.github.io/book/) it took me about half an hour to install Rust from scratch, build and flash for the first time. The Rust tooling is very impressive and makes this kind of thing very easy. I'm happy to send you a binary, but you may find it faster to make your own...

**Comment by gkasprow** [comment]
I usually use IDE tools for C language under Windows (Atollic IDE) and STM32CubeMX. Never used RUST.
I have a virtual Linux machine but it always takes some time to set it up.

**Comment by gkasprow** [comment]
I'm looking at the DAC reference input and it's fine.

**Comment by hartytp** [comment]
@gkasprow here is a hacked version of @jordens fw. On power on, it sets DAC 0 to +fs and DAC 1 to -fs. I checked on a scope and I can clearly see the oscillations I posted before.




[release.zip](https://github.com/sinara-hw/Stabilizer/files/3329391/release.zip)

**Comment by gkasprow** [comment]
@hartytp I took your files. It is elf output. I converted using 

> arm-none-eabi-objcopy -O ihex

then converted to dfu and CPU doesn't start.

**Comment by gkasprow** [comment]
Actually it does something. both DACs are now set to -10V. And still no issues.
![tek00009](https://user-images.githubusercontent.com/4325054/60212570-dd168100-9861-11e9-900e-3e04dfe505eb.png)

**Comment by gkasprow** [comment]
This time I supplied it from linear bench supply.

**Comment by hartytp** [comment]
@gkasprow one DAC should be at +10v and one at -10V. Maybe it's not flashed correctly? Try following the instructions at https://github.com/quartiq/stabilizer for how to flash via DFU

It's possible that the noise is related to CPU activity so if the CPU isn't running then maybe the noise is gone (although, halting execution from GDB didn't make an impact on the noise I saw so I don't think that's the case).

**Comment by gkasprow** [comment]
It's quite possible that it comes from the CPU.
I followed instruction, I do the verification.
![obraz](https://user-images.githubusercontent.com/4325054/60215602-49947e80-9868-11e9-8107-c6994b1a9e1e.png)

![obraz](https://user-images.githubusercontent.com/4325054/60215585-3d102600-9868-11e9-9802-09ef7a316a70.png)

**Comment by gkasprow** [comment]
Ethernet makes huge difference
![tek00010](https://user-images.githubusercontent.com/4325054/60215858-e3f4c200-9868-11e9-9c5e-304fb7fded54.png)

**Comment by hartytp** [comment]
All the tests I did were with Ethernet connected btw.

**Comment by gkasprow** [comment]
did you set the option bytes?

**Comment by hartytp** [comment]
> It's quite possible that it comes from the CPU.
> I followed instruction, I do the verification.

Interesting. I'll re-flash my board with DFU tomorrow and check that the files I posted do what I think they should :) I'll also see what happens when I remove the ethernet connector

**Comment by hartytp** [comment]
> did you set the option bytes?

?

**Comment by gkasprow** [comment]
the CPU has a FLASH region that can be programmed called Option Bytes.

**Comment by gkasprow** [comment]
It looks like these interferences go through the output CMC.
When I short pins 9, 10 of the AFE connector, the output gets clean.

**Comment by hartytp** [comment]
> the CPU has a FLASH region that can be programmed called Option Bytes.

Pass. Not sure

**Comment by hartytp** [comment]
> It looks like these interferences go through the output CMC.
When I short pins 9, 10 of the AFE connector, the output gets clean.

Good to know. I'll try that tomorrow as well.

What's your model here? That the CMC picks up noise? Or that having the DAC SMA ground floating at AC is a bad idea for noise?

**Comment by jordens** [comment]
https://github.com/sinara-hw/Stabilizer/issues/9#issuecomment-499116829

**Comment by gkasprow** [comment]
No, CMC is just a transformer. It's good at removing the common noise, but it does well under one assumption that both lines have the same load impedance. Which is not true in our case.
The CMC part that is connected to GND breaks the ground loop created by Ethernet switch, PoE transformer capacitance, oscilloscope, etc. this loop has low impedance for high frequencies, that's why we observe short spikes. The CMC part that is connected to the signal sees only 1M scope impedance.

**Comment by jordens** [comment]
What does that mean for the cmcs on zotino, sampler and idc2bnc? They are also typically used across severe impedance mismatches.

**Comment by gkasprow** [comment]
It strongly depends on the particular application. Maybe we should add an option to bypass the CMCs. Or even not mount them and provide small PCB with CMC and SMA connectors.
In Sampler the CMC is loaded in a symmetric way. In Stabilizer case, the voltage induced by the ground loop is even 1V, so the CMS still does a good job removing it. However, due to an uneven load, the process is not optimal.

**Comment by jordens** [comment]
What would a proper "common mode ground loop suppressor" between a low impedance source (a DAC) and a high impedance sink (a trap electrode) look like? Would that need a CMC with a a turns ratio as the sqrt of the ratio of impedances?

**Comment by jordens** [comment]
Leave the option bytes at their default values.

**Comment by gkasprow** [comment]
The only valid turn ratio is 1:1, otherwise, it won't work as CMC.
The CMC has two impedances, common and differential. Common is usually in uH..mH range, the differential is in nH range. If the signal is passed in a symmetrical way, nothing happens because we have the same current in both windings and the signal sees only differential inductance. But when the circuit is asymmetrical, one winding will get higher current and another will get much smaller which means that CMC is no longer serving the purpose.  The signal will see the common inductance instead. If we terminate the DAC after the CMC, at least for high frequencies, the situation would vasty improve.

**Comment by jordens** [comment]
Interesting. I.e. a parallel R-C with the same R as the output R of the DAC/driver? Would be nice to see that tested.

**Comment by hartytp** [comment]
> It looks like these interferences go through the output CMC.
>When I short pins 9, 10 of the AFE connector, the output gets clean.

> #9 (comment)

Interesting. @gkasprow I believe the issue you're seeing here is entirely separate to the issue I saw. Firstly, the noise spectrum is different. Beyond that, I also tried both PoE and an external supply, as well as removing the ethernet. I do not recall any of this making a significant difference (but will double check next week). Given all that and the fact that the noise scaled linearly with the DAC output voltage, I don't think that what I saw was a grounding issue.

I'll try shorting the CMC next week to be sure.

It's interesting you weren't able to reproduce my findings, but maybe not surprising since the DAC output voltages were not correct during your tests. I'll re-flash the binaries I posted next week and take a few measurements to see if I can figure this out.

**Comment by hartytp** [comment]
> What does that mean for the cmcs on zotino, sampler and idc2bnc? 
> ...
> It strongly depends on the particular application.

Indeed. That's the problem with these grounding issues -- it's hard to find a solution that works in all cases.

FWIW on all the tests I've done on the other boards, I've never seen the CMCs do any harm.

> Maybe we should add an option to bypass the CMCs. 

Can we fit jumpers across the AFE headers? Ship the board with the jumpers in and allow users to remove them as desired?

> What would a proper "common mode ground loop suppressor" between a low impedance source (a DAC) and a high impedance sink (a trap electrode) look like?
> ...
> If we terminate the DAC after the CMC, at least for high frequencies, the situation would vastly improve.

Yes, for a trap DAC, it's probably best to use RCs to make a symmetric differential AC termination.

**Comment by hartytp** [comment]
> If we terminate the DAC after the CMC, at least for high frequencies, the situation would vastly improve.
>...
> Interesting. I.e. a parallel R-C with the same R as the output R of the DAC/driver? Would be nice to see that tested.

Interesting idea.

Another approach might be to move the 30R output resistor (there to isolate the OpAmp from capacitive loads and keep it stable) to after the CMC. Put 30R on both the signal and ground with a small capacitor between the two outputs to make a high-frequency differential filter/termination.

What do you think @gkasprow? Can you try one of these approaches and see if they improve things?

Also, could you try adding the bypass capacitor (and ideally the CMC if possible0 the the PoE module and see if that helps to remove this noise?

**Comment by gkasprow** [comment]
I implemented the PoE CMC and bypass caps.
For CMC it does not really matter where this 30R is because it does not influence the current which passes through the inductor.

**Comment by hartytp** [comment]
I still feel like one wants inductors here rather than cmcs. What about an emi filter like the murata ones that do everything?

**Comment by gkasprow** [comment]
Let's also add the inductors. the Murata filter has too low inductance - it is essentially a few ferrite beads and capacitor. CMCs are needed, otherwise, we will end up with large inductors.
In higher power SMPS designs based on FLyback converters, there is usually an inductor before the CMC, that filters the non-common mode ripples.

**Comment by gkasprow** [comment]
I'm not sure if we can add any high capacitance at the input because it can break the power level negotiation process

**Comment by hartytp** [comment]
Did you fix the ref buffer capacitor?

**Comment by gkasprow** [comment]
yes

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/64458402-89dc6c80-d0f5-11e9-844e-3a993846a5f5.png)

**Comment by hartytp** [comment]
Great!
