### ISSUE TITLE
clocking via EEM

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#18]
* could be interesting for RTIO-synchronous applications
* maybe the HSE (PH0/1, OSC_IN/OUT) xtal is not really needed: the HSI might work but is less accurate
* would connect OSC_IN to an EEM LVDS pair

**Comment by gkasprow** [comment]
Added 0R option to connect one of EEM signals to the PH0/OSCIN. Crystal and capacitors
