### ISSUE TITLE
AFE headers

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#22]
The AFE headers on the boards supplied by Technosystem do not match the 3D model and aren't the same as the ones on the BOM. Moreover, the stand-off height is a couple of mm different for one of the headers.

If we're going to use these for mounting AFE mezzanines then the stackup height must be the same for all three connectors and must match the 3D model.

@gkasprow please double check the connectors you've used and add a note somewhere that they cannot be substituted for generic shrouded headers.

**Comment by gkasprow** [comment]
@hartytp can you take photo of these headers?

**Comment by hartytp** [comment]
I’m away this week but will do that next week when back.

**Comment by hartytp** [comment]
@gkasprow I had a go at this, but it's hard to get a photo that clearly shows the issue.

Two of the headers seem correct (measuring the dimensions, they seem to match the data sheet for the part in the BOM). However, one is significantly (>0.5mm) different and ruins the board-board stackup. Even by eye, one can see that it's different to the others.

At a guess, I'd say that someone substituted one of them for a generic part number that they already had in stock. However, to allow reliable board-board stackup these must not be substituted and should be marked as such in the BOM.

**Comment by gkasprow** [comment]
On the photo, the J3 looks different than other headers.

**Comment by hartytp** [comment]
Sounds about right.

**Comment by gkasprow** [comment]
All AFE connectors are 3M N25xx series so it is not an issue related with the project.

**Comment by hartytp** [comment]
Okay, we just need to tell ts not to make substitutions unless parts are explicitly labelled as generic

**Comment by dtcallcock** [comment]
Still an issue in v1.1

![IMG_8018 copy](https://user-images.githubusercontent.com/20587606/72285322-bb12ff00-35f7-11ea-86c4-fdf3353f91c7.jpg)

![IMG_8019 copy](https://user-images.githubusercontent.com/20587606/72285351-c9f9b180-35f7-11ea-9c25-5513f51b23ef.jpg)

**Comment by hartytp** [comment]
For now I suggest that the mating headers on afes like pounder are shipped unsoldered and soldered in situ by users

**Comment by pkozakiewicz** [comment]
We usually use generic connectors for all Sinara boards except 2x15 IDC. Unfortunately somehow I haven't seen this issue yet, so our team took what we had in our warehouse and assembled it. I see that for now Stabilizer is the only board designed for board-board stackup, so we have to pay attention to it next time. I understand that every functionality works properly.

**Comment by hartytp** [comment]
@gkasprow  Is there anything we can do here to avoid this issue in future? e.g. can we add a note on the BOM that these must not be substituted?

**Comment by gkasprow** [comment]
Good idea to add the note to the BOM

**Comment by gkasprow** [comment]
I added note "Use original! " to the BOM
