### ISSUE TITLE
output cmc

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#27]
we should make a decision about what to do here: leave it as is? scrap CMC? fit jumpers to short the CMC by default? add a differential output filter?

I'm happy with it as is, since I haven't yet observed any situation where the CMCs make things worse by a significant amount. I'm also happy scrapping since I haven't seen them make anything better yet.

**Comment by gkasprow** [comment]
One can always add one outside of the board when it's necessary. I'm not sure if there are such ones with SMA connectors. We can always make a tiny PCB with CMC, RC pads and SMA connectors

**Comment by jordens** [comment]
I would like to have them bypassed or even scrapped/DNPed by default. With PoE they make it significantly worse. sinara-hw/Thermostat#31 and #17 may or may not resolve this.

**Comment by hartytp** [comment]
I don't have any objection to scrapping the output CMCs.

**Comment by gkasprow** [comment]
added 0R mounted by default. CMCs are DNP by default.
