### ISSUE TITLE
Digital input labelling incorrect

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Stabilizer#33]
The front panel input DI0 connects to the signal labelled DI1 and vice versa.

Proposed solution: change the schematic labelling, leaving the front panel labelling / order and CPU pinout unchanged, so the firmware remains compatible across the different board versions.

**Comment by gkasprow** [comment]
we will need anyway new firmware for CPU so I'd fix the labels on CPU as well.
I will also add firmware version pins.
