### ISSUE TITLE
EEPROM (U6) only powered from EEM management power

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Stabilizer#34]
The EUI48+EEPROM (U6) is powered from P3V3_MP - this is only driven from the EEM connector, so is not powered when the Stabilizer is running stand-alone. 

We should change this so that the EEPROM is powered when the Stabilizer is running standalone.

**Comment by gkasprow** [comment]
This was already implemented "added P3V3_MP supply path during stand-alone operation"

**Comment by cjbe** [comment]
@gkasprow great! This fix does not seem to have been pushed yet - I checked on the current master and the issue is still there.
