### ISSUE TITLE
IC12 compensation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#38]
This looks a little different to the data sheet, since you've added the RC compensation to the FB pin. I don't have any reason to suspect an issue here but, as always, I'm curious :) Where did the design come from and are you definitely happy with the component values? If so, please close.

**Comment by gkasprow** [comment]
The last row of the table
![obraz](https://user-images.githubusercontent.com/4325054/64472700-cdb98b00-d162-11e9-8046-97615ff77521.png)

**Comment by gkasprow** [comment]
I've just noticed that I used wrong inductance. It should be 4.7uH instead of 6.8. I simply copied this design from another project where it works already for years.

**Comment by hartytp** [comment]
Okay if you’re happy with that, it’s just odd to me that you’ve added extra compensation not mentioned in the data sheet. If you’re happy with t it’s fine by me though

**Comment by gkasprow** [comment]
These compensation components are mentioned in the datasheet, in the table.
But you are right, it is not easy to find them.
