### ISSUE TITLE
IC7 output capacitor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#40]
Isn't this the same part we have issues with on Urukul?

I'm a bit worried about stability here. Should we consider adding a large ceramic in parallel with the electrolytic to help ensure stability?

**Comment by gkasprow** [comment]
I changed C55 100nF -> 1uF

**Comment by hartytp** [comment]
Nb this also applies to the other similar regulator on that page

**Comment by gkasprow** [comment]
OK, right.

**Comment by hartytp** [comment]
So that's IC7 IC26 and IC4

**Comment by hartytp** [comment]
oh and IC13. So, most of the LDOs :)
