### ISSUE TITLE
altium project issue

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#44]
opening the project on a fresh clone, I get the message 
![image](https://user-images.githubusercontent.com/21218399/64479153-ca49f200-d1aa-11e9-9669-14f6b09ad641.png)

**Comment by gkasprow** [comment]
the file is there, but it seems the prjpcb is outdated. Try now.

**Comment by hartytp** [comment]
Thanks Greg. I'll check again next time I'm at a PC with allium

**Comment by gkasprow** [comment]
I did repo clone and it opens without issues.
