### ISSUE TITLE
copy fastino filter design

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#45]
Since this is ready in time after all, any objections to porting Stabilizer to it? Lower cost, lower power consumption, lower noise. More component reuse between designs.

**Comment by dnadlinger** [comment]
The (simulated) transient response is currently considerably faster-settling on Stabilizer – there is probably some room for optimisation by fudging component values, though:

<img width="547" alt="Screenshot 2019-09-07 at 9 16 17 PM" src="https://user-images.githubusercontent.com/19335/64479847-c8852c00-d1b4-11e9-8198-924269d28280.png">

**Comment by hartytp** [comment]
![image](https://user-images.githubusercontent.com/21218399/64480046-6fb79280-d1b8-11e9-91e4-f88af94fc152.png)

**Comment by hartytp** [comment]
Are you happy with this as your optimized filter design?

**Comment by hartytp** [comment]
The DAC settling time is 1us, so this isn't much slower than that. I'm happy with that settling time for Stabilizer personally.

**Comment by hartytp** [comment]
(at least, I think the benefits of the new filter design outweigh the downside of a slightly slower response)

**Comment by gkasprow** [comment]
@hartytp do we want to change the reference for Stabilizer DAC as well? We would need to add dedicated 5V one or switch ADC to 5V. It's a bit of extra work.

**Comment by gkasprow** [comment]
We can simply replace DAC resistances with external SOT-23 matched resistor to limit the noise and leave the rest as it is now.

**Comment by hartytp** [comment]
Yes I’d forgotten about the different reference. In that case I’d say the current afe is fine for stabilizer even if it’s not optimal. Let’s leave as is
