### ISSUE TITLE
SI

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Stabilizer#46]
SPI [termination ](https://github.com/sinara-hw/Pounder/issues/9)

**Comment by hartytp** [comment]
Do you plan to do this for the next release?

**Comment by gkasprow** [comment]
Yes, I have a config file so doing it for the next revision is quick

**Comment by gkasprow** [comment]
I meant SI/PI analysis :) Of course I will do both

**Comment by gkasprow** [comment]
I added 50R source termination resistors on SPI lines, the lines are also 50Ohm ones. I don't know the driver resistance of STM32 chip, we can always change the resistors in case of issues

**Comment by gkasprow** [comment]
6V rail
![obraz](https://user-images.githubusercontent.com/4325054/64926068-5d150d00-d7f9-11e9-882a-76ae08e13470.png)

-13V rail
![obraz](https://user-images.githubusercontent.com/4325054/64926081-7918ae80-d7f9-11e9-888f-527deb2e4b50.png)

+13V rail
![obraz](https://user-images.githubusercontent.com/4325054/64926091-9483b980-d7f9-11e9-8b8c-a57e2d93b8cb.png)

P12V0 rail
![obraz](https://user-images.githubusercontent.com/4325054/64926156-7bc7d380-d7fa-11e9-96ed-1ca49201f241.png)

P3V3
![obraz](https://user-images.githubusercontent.com/4325054/64926171-a7e35480-d7fa-11e9-8428-11444e382d8c.png)

**Comment by gkasprow** [comment]
DC drop was well below 30mV including inductors for all rails.
