### ISSUE TITLE
ESD Zener on PoE

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#49]
@gkasprow should we add a Zener diode on the PoE module input to protect against EMI?

**Comment by gkasprow** [comment]
I assume you mean TVS. I'm not sure we need it. There is already CMC and LC filter that protects against ESD. The only thread that can break the PoE module is severe overvoltage which comes from broken switch or dummy power injector.

**Comment by hartytp** [comment]
ok
