### ISSUE TITLE
usb connector position

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#51]
I noticed that the shielded Schroff panels are quite (~1mm?) a bit thicker than the old unshielded ones that the request to move the USB connector further back (#11) was based on.

Just move the connector back so that it's legs don't interfere with the panel (as they did in #11) but not any further. I.e. so that it's shield still fits into the panel cutout.

This also affects Thermostat.

The thicker panels makes the requirement to never use the metal SMA locking washer if the plastic washers are used even more important.

**Comment by gkasprow** [comment]
I already did it. Please add an issue for Thermostat.
