### ISSUE TITLE
QSPI

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Stabilizer#53]
Consider routing QSPI to the extension connector instead of GPIO.
Another option is to add yet another high speed connector for 200Mbit QSPI link

**Comment by hartytp** [comment]
> Another option is to add yet another high speed connector for 200Mbit QSPI link

If you can find something wit the right stackup, what about replacing all three connectors we currently have with a single Samtec connector (something like a lower pin-count FMC)?

**Comment by hartytp** [comment]
Or, hell, go the full way and just use FMCs. i.e. make two front-pannels for Stabilizer: one which is the standard 4HP FP, and one with is 8HP with an AFE mezzanine cutout. Then put an FMC (or similar connector with fewer pins) and route all analog/digital lines on to that. 

That might actually work out nicer than the current design, since getting the stackup both electrically and mechanically reliable using separate FPs and pin headers can actually be a bit of a pain...

Thoughts?

**Comment by gkasprow** [comment]
going this way, we can reuse Sayma AFE form factor and connector signal assignment...

**Comment by gkasprow** [comment]
The issue with BGA connectors is that you cannot make such AFE at home...

**Comment by hartytp** [comment]
@jordens what was your conclusion about all of this? What (if any) changes do you want to make for pounder?

**Comment by jordens** [comment]
I think there is a pounder issue for this.

**Comment by dtcallcock** [comment]
https://github.com/sinara-hw/Pounder/issues/10

**Comment by hartytp** [comment]
Thanks for the link. Can someone more familiar with the microprocessor pin functions confirm what if any changes that requires to stabilizer please?

This is the last issue, so I’m keen to close ASAP and get v1.1 off to manufacture

**Comment by jordens** [comment]
I guess @gkasprow will propose those changes. Connect QUADSPI to the AUX header instead of the SPI1 bus that is connected now. Drop LPUART1_TX and PC8 and use those for the two additional QUADSPI data pins.
After https://github.com/sinara-hw/Stabilizer/issues/13#issuecomment-528980208 it would then make sense to wire SPI1 to the EEM header instead of SPI6.

**Comment by gkasprow** [comment]
@jordens we need both SPI and QSPI.
I will connect it instead of 
PD10
LPTIM1_OUT
HRTIM_CHE1
HRTIM_CHE2
HRTIM_CHA1
HRTIM_CHA2

I can also choose other pins instead

**Comment by jordens** [comment]
Do we need both SPI and QSPI? I'd rather have timers available on the mezzanine.

**Comment by gkasprow** [comment]
We need SPI for attenuators in Pounder and QSPI for DDS.
but, we can also connect it instead of 
LPUART1_TX
PC0
PD10
PC8
UART4 Rx
and one selected timer lines. 

The QSPI lines have also some useful alternative functions:
IO3
![obraz](https://user-images.githubusercontent.com/4325054/67605455-b8cea080-f77e-11e9-9208-6e1e95aa1928.png)

IO2
![obraz](https://user-images.githubusercontent.com/4325054/67605481-c8e68000-f77e-11e9-8f53-60271149a27f.png)

IO1
![obraz](https://user-images.githubusercontent.com/4325054/67605496-d56ad880-f77e-11e9-90db-98538ea85f2a.png)

IO0
![obraz](https://user-images.githubusercontent.com/4325054/67605518-e0256d80-f77e-11e9-8da8-489188bd8eed.png)

CLK
![obraz](https://user-images.githubusercontent.com/4325054/67605541-ed425c80-f77e-11e9-8689-31196a626a44.png)

NSS
![obraz](https://user-images.githubusercontent.com/4325054/67605601-14992980-f77f-11e9-9ab6-6d2008570522.png)

**Comment by jordens** [comment]
OK. UART is less useful for the mezzanine IMO. We also have another header for a uart.
From my perspective either set of pins is fine.

**Comment by gkasprow** [comment]
I mean that we already have this UART line among QSPI lines :)

**Comment by gkasprow** [comment]
The header has the following pinout
![obraz](https://user-images.githubusercontent.com/4325054/67617055-91f48680-f7df-11e9-9f22-a33ac8d790e6.png)

**Comment by gkasprow** [comment]
update

**Comment by hartytp** [comment]
Cool. Can you post a new rc pdf please?

**Comment by gkasprow** [comment]
Sure, let me finish the routing. I also added QSPI source termination.

**Comment by hartytp** [comment]
Ok. But if people request final changes to the schematic don’t you want to hear them before you do the routing?

**Comment by jordens** [comment]
that pinout is fine from my perspective.
