### ISSUE TITLE
ERC fail

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#56]
@gkasprow am I going crazy, or did you not run ERC? We were having some odd issues with the internal DACs, so I did some probing. The DAC reference voltage was at 3.7V (the 3V3 rail runs at 3V4 because of resistor choices, so this is clipping of an ESD diode). The 2V048 reference at C75 is fine, but the output of IC27B is railing. When I touch the input pin of that OpAmp with a probe the output voltage disappears for a moment...

Looking at the schematic, I don't see a black dot here...

![image](https://user-images.githubusercontent.com/21218399/66244994-f782b500-e702-11e9-90f4-3160118cf08d.png)

The input is pin 5 of the OpAmp

![image](https://user-images.githubusercontent.com/21218399/66245008-05d0d100-e703-11e9-93fc-2791db076e51.png)

but there is no connection visible on the layout

![image](https://user-images.githubusercontent.com/21218399/66245022-15e8b080-e703-11e9-8d5d-f5100bf9ae73.png)

Did you forget to run ERC on this design ;)

@pathfinder49 I think this may explain some of the odd "firmware" issues you've been debugging

**Comment by hartytp** [comment]
Not sure if this will have killed the CPU DACs.

**Comment by hartytp** [comment]
@pathfinder49 we should be able to fix this easily by soldering a wire from that OpAmp to C75. Let me know if you want a hand doing that? Once it's done, check the output isn't oscillating and increase the 10R resistor if you need to to stabilize things.

**Comment by gkasprow** [comment]
You are right. AD is even placing a red warning under the IC27B input.
I always do ERC, but for some reason, I skipped this one. No faintest idea of how this happened.

**Comment by hartytp** [comment]
Np it’s an easy fix

**Comment by gkasprow** [comment]
done. I also fived it on the board I got from @sbourdeauducq for debugging PoE
