### ISSUE TITLE
increase R95?

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#57]
Is 10R enough to keep the OpAmp happy with all that capacitance? Does the CPU draw much reference current or can we increase to, say, 100R to make sure the OpAmp doesn't get upset?

![image](https://user-images.githubusercontent.com/21218399/66245075-6e1fb280-e703-11e9-9e6a-9186e06dbbf3.png)

**Comment by gkasprow** [comment]
I usually place just 10R in such cases and so far never had any issues.

**Comment by hartytp** [comment]
Ok. I normally use 30R here. If you’re satisfied then close, but personally I’d make it a little bigger to be safe

**Comment by gkasprow** [comment]
OK, let's use 30R to make you sleep better :)

**Comment by hartytp** [comment]
:)
