### ISSUE TITLE
PoE small tweaks

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#59]
- [x] are you happy with the trace clearances on the HV inputs? Shouldn’t they be rated for 1kV breakdown?
- [x] please can you add pads for sense resistors on the PoE inputs? Also test points. That way if we do have further issues they will be much easier to debug

**Comment by gkasprow** [comment]
we care only about the separation between PoE HV inputs and the rest of the circuits. The clearance between HV inputs can be much lower.
I found that on negative layer there was not enough clearance.

Otherwize, the  clearance of at least 1mm is preserved.

**Comment by gkasprow** [comment]
I added special HV clearance rule

**Comment by gkasprow** [comment]
...and a lot of not obvious violations appeared :)

**Comment by hartytp** [comment]
DRC is a wonderful tool
