### ISSUE TITLE
Rc2 review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#62]
Thanks @gkasprow !

I’d like to send this to production on Monday afternoon. Please give feedback before then (or let me know if you need longer before we close this round).

**Comment by hartytp** [comment]
- [ ] Why is Ic1B1C DNP?
- [ ] why is R124 undefined, not DNP?
- [ ] Was it the LT1763 that caused trouble on Urukul? Should we consider replacing it something more reliable like an LT3042? This would have the advantage of removing a BOM line.

Other than that, review complete. All looks good to me!

**Comment by hartytp** [comment]
That comment about the LDO applies to +12V and +5V0A rails, but note the errata from Fastino.

Before changing, can you confirm that the LT1763 was indeed the part that caused issues on Urukul please?

Note that the review was only a look over the change log and not a full design review.

**Comment by hartytp** [comment]
- [ ] Didn't you plan to replace SS16 with something rated to a higher voltage? Also, are you happy with the breakdown voltage of the FET. Since we don't have a TVS here and these components are before the EMI filter, we need to make sure that they can handle the maximum possible voltage spike (or just add a TVS to be safe!)

**Comment by hartytp** [comment]
- [ ] Is the annotation about the OpAmps having JFET inputs true with the new opamps?

**Comment by hartytp** [comment]
- [ ] are the dac output simulations updated for the new OpAmps?

**Comment by hartytp** [comment]
- [ ] NB LT3042 needs 4.7uF min output capacitance. FWIW if we don't make this change we should, at the very least, increase IC16's output capacitance from 100nF to help ensure stability

**Comment by hartytp** [comment]
Ok, now I'm done. :)

**Comment by gkasprow** [comment]
The PoE rectifier uses 60V diodes. I can switch to 80V ones, but they have a [150mV higher](https://www.soemtron.org/downloads/disposals/ss14.pdf) voltage drop. However, PoE [spec](http://www.ieee802.org/3/poep_study/public/mar05/diamond_1_0305.pdf) says that max voltage is 57V, most switches use 48V though.

**Comment by hartytp** [comment]
Ol if you think it’s fine then leave it as is

**Comment by gkasprow** [comment]
>  Why is Ic1B1C DNP?

To lower the latency.

> 
> why is R124 undefined, not DNP?

I made it DNP. It's a placeholder.

> Is the annotation about the OpAmps having JFET inputs true with the new opamps?

They have 5pA of input bias, but they are not JFET. I changed the note.

I added 60V TVS as well.

**Comment by gkasprow** [comment]
I also replaced the LT1763 LDOs with LT3042

**Comment by gkasprow** [comment]
new release
https://github.com/sinara-hw/Stabilizer/releases/tag/v1.1rc3

**Comment by hartytp** [comment]
I can't see any issues with this design. Looks really lovely @gkasprow thanks again.
