### ISSUE TITLE
LT304x fast start

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Stabilizer#68]
https://github.com/sinara-hw/Stabilizer/issues/65#issue-529266345

Should we apply this to other Sinara designs?

**Comment by gkasprow** [comment]
Some designs that use PG output already have this implemented. So, yes, let's add it to all designs that use this IC

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/95663448-a4c2b100-0b3f-11eb-9a76-587839132a86.png)
