### ISSUE TITLE
v1.1 Testing

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Stabilizer#69]
My boards arrived today - they look very nice.

It looks like Technosystem applied a manual rework to fix #67 

Were any other fixes applied?  
What, if any, testing has been done on the boards they shipped?

**Comment by gkasprow** [comment]
Only basic things were tested since we don't have an automated test suite yet:
DAC + output amplifier
ADC front-end and driver
CPU booting + USB
PoE and DC supply
all power rails

**Comment by hartytp** [comment]
Doesn't seem to be anything else here so closing.
