### ISSUE TITLE
PoE vs. EEM power conflict

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Stabilizer#72]
Currently the behavior of Stabilizer when installed in a Kasli crate is rather nasty:
* If you don't connect the EEM cable, the user needs to power it via PoE, which is less common than regular Ethernet. The power from Kasli cannot be used in a simple way.
* If you do connect the EEM cable, and the user later connects a PoE source, then Stabilizer powers Kasli and other EEMs, and may even also apply power in reverse to any plugged-in power supply adapter. In general, there is, in several places, insufficient current handling capability for that.

I propose:
* Add hardware so that the EEM port by default can only act as a current sink.
* Under MCU command, the EEM port may act as a current source.
* Add a current limit on the EEM port so that if power is inadvertently applied (e.g. due to a firmware problem) to a Kasli system through the Stabilizer EEM cable, the issue will be detected and no excessive current will flow anywhere.
* The current limit, when it triggers, should disconnect EEM power permanently and notify the MCU. EEM power can be re-established with a pulse (or I2C command or similar if we use a fancy IC and not discrete logic) coming from the MCU.

**Comment by gkasprow** [comment]
This can be done easily with ideal diode (2 transistors + 2 resistors) opamp and a few lines of code.

**Comment by gkasprow** [comment]
@sbourdeauducq the Stabilizer can also be powered by a barrel connector or Molex connector.

**Comment by sbourdeauducq** [comment]
Okay, we probably want a diode there so it only acts as a current sink, e.g. when PoE is connected at the same time.

**Comment by gkasprow** [comment]
OK

**Comment by gkasprow** [comment]
I prefer ideal diodes over standard diodes :)

**Comment by sbourdeauducq** [comment]
Sure :)

**Comment by gkasprow** [comment]
I added an ideal diode circuit. It also enables powering the EEM from PoE on request.
![obraz](https://user-images.githubusercontent.com/4325054/95663929-9a0a1b00-0b43-11eb-86f5-10322fb7e187.png)
I'm not sure if latched overcurrent protection in the case of firmware malfunction is really needed. It would complicate the design and cause additional confusion to the user.
The PoE will switch off after exceeding the allowable power something should break here.
I can also add a simple current monitoring circuit that will warn the CPU that we are exceeding the safe current operation - let's say 90% of the PoE module max current. The Stabilizer consumes 160mA of idle current. With Pounder it consumes 552mA. Let's warn the CPU when the EEM current exceeds 2A. 
One solution is to use the current sense amplifier like in the Booster. It adds 3$ to the BOM.
![obraz](https://user-images.githubusercontent.com/4325054/95664923-fec97380-0b4b-11eb-85c5-4bebf395f3cc.png)




Another solution is to use 4BJTs and MOSFET RDSon - it's very low cost but not precise. It may also cause issues bypassing disabled FET.
![obraz](https://user-images.githubusercontent.com/4325054/95664735-e4db6100-0b4a-11eb-8d6f-c1af3015b757.png)

**Comment by gkasprow** [comment]
@sbourdeauducq are you happy with such solution?

**Comment by sbourdeauducq** [comment]
> I'm not sure if latched overcurrent protection in the case of firmware malfunction is really needed. It would complicate the design and cause additional confusion to the user.
> The PoE will switch off after exceeding the allowable power, nothing should break here.

Okay, fair enough. Let's just go with the ideal diode + Force_EEM_Source circuit then, without additional current limit or monitoring.

**Comment by gkasprow** [comment]
OK, done
