### ISSUE TITLE
v1.1 bad power connection

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#75]
* The rear barrel connector uses L712RA which needs 11 mm long barrel connectors. v1.0 had L712RAS which requires the more common 9 mm. Please finally harmonize with Kasli, Humpback, and whatever else has that barrel connector. Also note that the short one does not allow locking nut usage with a front panel.

![image](https://user-images.githubusercontent.com/1338946/83768676-5d9f4d80-a67f-11ea-8ed7-e850746f6a86.png)
![image](https://user-images.githubusercontent.com/1338946/83768694-61cb6b00-a67f-11ea-804a-99e97263687f.png)

* Three of the power outer connector pin's thermal relief spokes are missing. The remaining one looks like a pretty fragile link.

![image](https://user-images.githubusercontent.com/1338946/83768431-0f8a4a00-a67f-11ea-9023-6f5c9fd967f8.png)

**Comment by gkasprow** [comment]
well, this was a part of the harmonization process :)
Kasli, Thermostat, Stabilizer, Humpback, Banker, Clocker, Fast_Servo, VHDCI carrier are using SWITCHCRAFT 712RA
Locking is critical, that's why we sticked with 712RA

**Comment by gkasprow** [comment]
fixed PCB
![obraz](https://user-images.githubusercontent.com/4325054/95676412-40930200-0bbe-11eb-8604-e2093f8df467.png)
