### ISSUE TITLE
Clean up PA0 for timing input from Pounder

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#78]
https://github.com/sinara-hw/Pounder/issues/76#issuecomment-679079240

For Stabilizer v1.2 this just means leave J10:18 to PA0 (as now) and clean up the PA0 wire for crosstalk and impedance and add DNP parallel AC termination. The rest can be done on Pounder, I think.

**Comment by gkasprow** [comment]
added AC termination
![obraz](https://user-images.githubusercontent.com/4325054/95665396-1efb3180-0b50-11eb-9baa-be3522454cdc.png)
fixed trace impedance
![obraz](https://user-images.githubusercontent.com/4325054/95665445-7f8a6e80-0b50-11eb-84d4-e0934c4e32fc.png)
