### ISSUE TITLE
panel

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Stabilizer#8]
@hartytp Please have a look at the panel
![obraz](https://user-images.githubusercontent.com/4325054/50935723-4994f380-146d-11e9-8c01-55f76f3a51a4.png)

**Comment by cjbe** [comment]
Is there sufficient clearance from the extraction handle to the ethernet socket? Everything else looks good to me.

**Comment by gkasprow** [comment]
yes, there is enough space.
![obraz](https://user-images.githubusercontent.com/4325054/51054312-c2ff2400-15dc-11e9-82b6-c2a2345a40f4.png)
