### ISSUE TITLE
P5V0A rail continuity

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#82]
It's not a high current rail, but it's still necked down a lot. A little strengthening like for the other rails would be good.

![image](https://user-images.githubusercontent.com/1338946/96418717-7bff8300-11f3-11eb-9d05-0dd545efafc3.png)

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/96516132-ddad0500-1266-11eb-860d-a8247f845de7.png)
