### ISSUE TITLE
PHY NRST pull-down

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#84]
There is currently only the internal pull-up on the PHY NRST.
Datasheet seems to indicate we must not deassert it until 25 ms after power supply up. Until the CPU sets up the pin and drives it low, the pull-up may deassert it early.
Can we add a ~10k pull-down?

c.f. https://github.com/quartiq/stabilizer/issues/154 https://github.com/quartiq/stabilizer/issues/141 https://github.com/sinara-hw/Stabilizer/issues/81 https://github.com/sinara-hw/Stabilizer/issues/76

![image](https://user-images.githubusercontent.com/1338946/96709162-9d4ea380-139a-11eb-9847-ecbafea16315.png)

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/96710520-7c874d80-139c-11eb-919d-275ea01dae5b.png)
