### ISSUE TITLE
wrong REV ID

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Stabilizer#89]
Stabilizer v1.2 still has REV ID =1

**Comment by sbourdeauducq** [comment]
Did you send any v1.2 boards to production with this problem, or will it get fixed before?

**Comment by sbourdeauducq** [comment]
Well I guess that it'll get fixed since this is simply a resistor setting.
What's the correct value?

**Comment by gkasprow** [comment]
it should be "2"
I don't know if that was already produced.
@kaolpr ?

**Comment by gkasprow** [comment]
CTI produced a batch of it.
@akaminska small fix needs to be done after the production.

**Comment by gkasprow** [comment]
the resistors can be removed and two shorts need to be installed
![obraz](https://user-images.githubusercontent.com/4325054/114900822-830af500-9e14-11eb-949d-3ea68937c2e2.png)

**Comment by gkasprow** [comment]
changed to 3 since we are adding one CPU pin function in rev1.3
