### ISSUE TITLE
DI0/1 input protection

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Stabilizer#90]
The buffer doesn't like high or low input voltages and will clamp.
Can we add 1k at the buffer input after the AC termination to limit the current?

![image](https://user-images.githubusercontent.com/1338946/106589455-54d38400-654c-11eb-87ca-75ad5c526696.png)

**Comment by gkasprow** [comment]
sure, if connect it to output specified as 5V TTL at 50R load it may even cause latch-up effect.
We should add a TVS and series resistor.
