### ISSUE TITLE
LT3042 fast start was added in v1.2?

### ISSUE THREAD

**Issue by dnadlinger** [sinara-hw/Stabilizer#93]
Seems like fast start for the analogue power rails was added in v1.2. I've amended the release notes in https://github.com/sinara-hw/Stabilizer/releases/tag/v1.2rc3 accordingly. @gkasprow: Could you please verify and either close this issue, or edit out the line out of the release description if that isn't in fact the case?

**Comment by gkasprow** [comment]
Yes, it was added in rev 1.2
